apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "gateway.fullname" . }}
spec:
  encryptedData:
    foo: AgAGAilXrB3TTDaq4fwiUwJeFgBGoLe9d6tyZw5YYoyfFsGDZme2nQXLsORiI7D4L29xGXq6cZh6mnBxa3Rv1OVhimjM50mNAfRYmEap+CMqQfRzSf+pQhViZOmt9LsnUzH9I1Q9ycYWvA86MjsXt5SNb/lSqfCq8/o7bmboOTj3zq3JQFXaobDsiyS+xJPnNivEPY3LLr3GLkQw2gIuLHTU+/9bsJ/pJnKk5lVa0uM75Zk/I7mu5ekXv1TeeYFrBN3XFeV+jyNOJrGIrw9sl81oMZmZkHJEIKWJVxz956fJxGIVnk3prBw4VS+hCoxmjmB5fhPThzA6J2qel+Ydc8i3a8MiMY542ef/8ZwCZ3SEE1W4zNrScZysv7/UM5UM1eRIZbu8ZUFwnG9LfxWODphjLqAXRrbqgDZ0UABO8FRqT4dHA3Z+xDpz2l64yksi/wO2fbis5HybMLDT/arjIwwQ5QSjX/r+uhhuUu44VOyd2Uj6Xe+JvlsvstmI/oNPoRT1l9/V+TIJs3cpE6b0C5bXc0s6hrDNxXvNbFA7aMKtAt+VLPYg/HEI5gfVaXlZk+ETWMWaHWGFeB5c2IZ6bz63NU7lc0T1Fl93F7QR2cKi3yYXJOdJvCiu5sDT30j45s9W7BYsZXVfZn20r95f5zvGkrXvwChpJzsLeQ88ze0Nf+iOkitB3p3m/GKA0npwqGIdT5A=
  template:
    metadata:
      name: {{ include "gateway.fullname" . }}
