apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "gateway.fullname" . }}
spec:
  encryptedData:
    foo: AgAl/0cq4DdeH5pfVYh6hyFLSXTblHWp8lHGQWPWwe2j89MeLzkYoJ8BvvlNy2a7ujKjYQ52spgzyI429MdPAMPZ6xABEUz+q8qQXOSIg6Z19ybjOq2UpckCAHY/91Zaz/YIEjv50elJsKV726Iy93WSv2S5mhoKme0MR9lIv3SLG6Kd1VMb2oW1q0Jge9ldzArFwb6ccUR950hXcwpMrd8Nqiz1pDG3WY7qxDuQCoDcDjof7w1Vw0UBmBDJKDX0yx8EpirBl1c2M4YHp92S6OxxUMaoB7fRaRchZnP0IBFcUTfiR9baXJeLnITu2Je1qGZbwxYg/5W0s44aQya7pe8KimjM3x8AEQPDTH4wwToljAbpCPBWagdfpkIHnmt2IBHj9bFVUtkXRsLMvFlcLl9BTwo6U1sadungzIruDDTOolf8JZhiW7XTNykSryQms811BX7dkAbiBz5E2Z7KgfyXB5lYnY1eNGChrSChAjDHEs4r3MBtC4RE1ikQ1pMnCRMMF1y70bAPONlK1md3uY4qBS8AnE26lPIKvfg1a/ohGSfnQ3Rl89i81wh25/CqDR9XDwo3MiFJgLUVgnRPV7gV9Q5Z23ddTcZPdZQcimCPWxXpQ1i5UHnkqrL9794IReuergYC0Bc/VhgEnOl1Ty+nkSXcbdrY8crAMYQROKgFhm9Hfd2o9Pnj5ToWE821fK1FtzM=
  template:
    metadata:
      name: {{ include "gateway.fullname" . }}
