apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "gateway.fullname" . }}
spec:
  encryptedData:
    foo: AgDLHHV5E5wUv94adJEpDkobQSqGbTHTw7o+wXZ6J4vS8kDT8V4Y9/xUfRYnY7CF9L6DMUzOC3WqRjrdPqoW6iM5TTMCtnkihYlvXahex/hM5ECp2JwTDG2NiIdpxZNhhsFSC5Zsi3hUZXqK4JQq7pGgH0Td9ka9Qc0gDe5B0p7JFA51dki3LqyEtXwcOLPnWF3r779AffnemUFvW4kkkcHJs8ygWPAosHjyQDo+GeUedB50EmPRu7rS4GKHwjcyGh52Niau/A9gA52SmmrSJBe2nNhoLR5XHxCQW5VNTIo4jZpIZaDxctmNwsE4o9nhGMwVFHzjcAliW2BDD0GLCp7g/6q9ox0KPCLag1n/6H/7BXLYWyCnJS/adOLu4TaXRVk2uF9cvU+nCdtH/hSJiIU5Qoqmx2OfHJNIBDjYTtE8CsxVExiOY+SFoHd+iKY0ZFigImDKDjze6+Rfz+YYMwnsduuxEPtIarTNGVUBGiZZd0AgIfI3k4VCVKWDAMc1TuIy/P9RCzG3nW+vPXNXSJLX4zoGQgBdo+/zRDDDCWv+5GzxPkf/uQDV3bkpIInmxZ9TR19mrqC+EcH3pFwo/JXSoCJTLReM4+F1mgashFFXb4DjWuU2Eqg28iMT+Cay/3asPWqurXNsHBvz8gUbdLGDcB7W9VNLRjFrm4EyGMGXXbPPQRTDJC5ak9OpXUmdXsiV36c=
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "gateway.fullname" . }}
