apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "gateway.fullname" . }}
spec:
  encryptedData:
    foo: "{{ .Values.sealedSecrets.foo }}"
  template:
    metadata:
      annotations:
          sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ include "gateway.fullname" . }}
