apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-env1
spec:
  destination:
    name: ""
    namespace: env1
    server: "https://kubernetes.default.svc"
  source:
    path: envs/env1/gateway
    repoURL: "https://github.com/ruslansavchuk/test.git"
    targetRevision: main
  sources: []
  project: gateway
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
