apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-env2
spec:
  destination:
    name: ""
    namespace: env2
    server: "https://172.25.0.3:6443"
  source:
    path: envs/env2/gateway
    repoURL: "https://github.com/ruslansavchuk/test.git"
    targetRevision: main
  sources: []
  project: gateway
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
