apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-env2
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: env2
    server: "https://kubernetes.default.svc"
  source:
    path: envs/env2/orders
    repoURL: "https://github.com/ruslansavchuk/test.git"
    targetRevision: main
  sources: []
  project: env2
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
